/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerMeeting;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;

/**
 *
 * @author Jnatn'h
 */
public class completedMeeting extends javax.swing.JDialog {

    private ControllerMeeting controller;

    public ControllerMeeting getController() {
        return controller;
    }

    public void setController(ControllerMeeting controller) {
        this.controller = controller;
        setListener();
    }
    private void setListener(){
        process.addActionListener(controller);
        discount.addChangeListener(controller);
        
    }
    public JTable getHaircutobt() {
        return haircutobt;
    }

    public void setHaircutobt(JTable haircutobt) {
        this.haircutobt = haircutobt;
    }

    public JLabel getLclient() {
        return lclient;
    }

    public void setLclient(JLabel lclient) {
        this.lclient = lclient;
    }

    public JLabel getLdate() {
        return ldate;
    }

    public void setLdate(JLabel ldate) {
        this.ldate = ldate;
    }

    public JLabel getLdiscount() {
        return ldiscount;
    }

    public void setLdiscount(JLabel ldiscount) {
        this.ldiscount = ldiscount;
    }

    public JLabel getLeyenda() {
        return leyenda;
    }

    public void setLeyenda(JLabel leyenda) {
        this.leyenda = leyenda;
    }

    public JLabel getLinvoice() {
        return linvoice;
    }

    public void setLinvoice(JLabel linvoice) {
        this.linvoice = linvoice;
    }

    public JLabel getLtotal() {
        return ltotal;
    }

    public void setLtotal(JLabel ltotal) {
        this.ltotal = ltotal;
    }

    public JButton getProcess() {
        return process;
    }

    public void setProcess(JButton process) {
        this.process = process;
    }

    public JTable getServicesobt() {
        return servicesobt;
    }

    public void setServicesobt(JTable servicesobt) {
        this.servicesobt = servicesobt;
    }

    public JSlider getDiscount() {
        return discount;
    }

    public void setDiscount(JSlider discount) {
        this.discount = discount;
    }
    
    
    /**
     * Creates new form completedMeeting
     * @param parent
     * @param modal
     */
    public completedMeeting(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Complete Meeting");
        setResizable(false);
         setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cat = new org.edisoncor.gui.panel.Panel();
        header = new org.edisoncor.gui.panel.Panel();
        center = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        process = new javax.swing.JButton();
        cent = new javax.swing.JPanel();
        linvoice = new javax.swing.JLabel();
        ldate = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lclient = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ldiscount = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        servicesobt = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        haircutobt = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        discount = new javax.swing.JSlider();
        jLabel9 = new javax.swing.JLabel();
        ltotal = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        leyenda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(440, 480));
        getContentPane().setLayout(new java.awt.CardLayout());

        cat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/fondo.png"))); // NOI18N
        cat.setMaximumSize(new java.awt.Dimension(464, 422));
        cat.setMinimumSize(new java.awt.Dimension(452, 497));
        cat.setPreferredSize(new java.awt.Dimension(452, 490));
        cat.setLayout(new java.awt.BorderLayout());

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/header/Meeting.png"))); // NOI18N
        header.setMaximumSize(new java.awt.Dimension(464, 75));
        header.setOpaque(false);
        header.setPreferredSize(new java.awt.Dimension(464, 75));
        header.setLayout(new java.awt.BorderLayout());
        cat.add(header, java.awt.BorderLayout.NORTH);

        center.setOpaque(false);
        center.setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(448, 30));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        process.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/process.png"))); // NOI18N
        process.setBorderPainted(false);
        process.setContentAreaFilled(false);
        process.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        process.setFocusPainted(false);
        process.setMinimumSize(new java.awt.Dimension(150, 30));
        process.setPreferredSize(new java.awt.Dimension(150, 30));
        process.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processActionPerformed(evt);
            }
        });
        jPanel1.add(process);

        center.add(jPanel1, java.awt.BorderLayout.SOUTH);

        cent.setBackground(new java.awt.Color(214, 209, 209));
        cent.setPreferredSize(new java.awt.Dimension(440, 0));

        linvoice.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        linvoice.setForeground(new java.awt.Color(0, 0, 0));

        ldate.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        ldate.setForeground(new java.awt.Color(0, 0, 0));

        jLabel3.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Invoice:");

        lclient.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        lclient.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Services obtained");

        ldiscount.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        ldiscount.setForeground(new java.awt.Color(0, 0, 0));

        servicesobt.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        servicesobt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Service", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(servicesobt);

        jLabel6.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Client:");

        jLabel7.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Haircut");

        haircutobt.setFont(new java.awt.Font("Serif", 2, 12)); // NOI18N
        haircutobt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Style", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(haircutobt);

        jLabel8.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Discount");

        discount.setFont(new java.awt.Font("Dialog", 1, 8)); // NOI18N
        discount.setForeground(new java.awt.Color(0, 0, 0));
        discount.setMajorTickSpacing(5);
        discount.setPaintLabels(true);
        discount.setPaintTicks(true);
        discount.setSnapToTicks(true);
        discount.setValue(0);
        discount.setOpaque(false);

        jLabel9.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Date:");

        ltotal.setFont(new java.awt.Font("Serif", 3, 12)); // NOI18N
        ltotal.setForeground(new java.awt.Color(0, 0, 0));

        jLabel11.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Total to pay:");

        javax.swing.GroupLayout centLayout = new javax.swing.GroupLayout(cent);
        cent.setLayout(centLayout);
        centLayout.setHorizontalGroup(
            centLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(centLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(centLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(linvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ldate, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(centLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lclient, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(centLayout.createSequentialGroup()
                        .addGroup(centLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, centLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ltotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(centLayout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(discount, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ldiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        centLayout.setVerticalGroup(
            centLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(centLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(centLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ldate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(linvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(centLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lclient, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(centLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(discount, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(ldiscount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(centLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ltotal, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        center.add(cent, java.awt.BorderLayout.CENTER);

        cat.add(center, java.awt.BorderLayout.CENTER);

        footer.setBackground(new java.awt.Color(0, 102, 255));
        footer.setOpaque(false);
        footer.setPreferredSize(new java.awt.Dimension(0, 30));
        footer.setLayout(new java.awt.BorderLayout());

        leyenda.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        leyenda.setForeground(new java.awt.Color(0, 0, 0));
        footer.add(leyenda, java.awt.BorderLayout.CENTER);

        cat.add(footer, java.awt.BorderLayout.SOUTH);

        getContentPane().add(cat, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void processActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processActionPerformed

    }//GEN-LAST:event_processActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.panel.Panel cat;
    private javax.swing.JPanel cent;
    private javax.swing.JPanel center;
    private javax.swing.JSlider discount;
    private javax.swing.JPanel footer;
    private javax.swing.JTable haircutobt;
    private org.edisoncor.gui.panel.Panel header;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lclient;
    private javax.swing.JLabel ldate;
    private javax.swing.JLabel ldiscount;
    private javax.swing.JLabel leyenda;
    private javax.swing.JLabel linvoice;
    private javax.swing.JLabel ltotal;
    private javax.swing.JButton process;
    private javax.swing.JTable servicesobt;
    // End of variables declaration//GEN-END:variables
}
