/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerHaircut;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;

/**
 *
 * @author Jnatn'h
 */
public class Rhaircut extends javax.swing.JDialog {

    private ControllerHaircut controller;
    public void setController(ControllerHaircut controller){
        this.controller = controller;
        setListener();
    }
    public ControllerHaircut getController(){
        return controller;
    }
    private void setListener(){
        
        grabar.addActionListener(controller);
        delete.addActionListener(controller);
        exit.addActionListener(controller);
        getPrice().addKeyListener(controller);
        
        
    }
    public JButton getDelete() {
        return delete;
    }

    public void setDelete(JButton delete) {
        this.delete = delete;
    }

    public JButton getExit() {
        return exit;
    }

    public void setExit(JButton exit) {
        this.exit = exit;
    }

    public JRadioButton getFemale() {
        return female;
    }

    public void setFemale(JRadioButton female) {
        this.female = female;
    }

    public ButtonGroup getGender() {
        return gender;
    }

    public void setGender(ButtonGroup gender) {
        this.gender = gender;
    }

    public JButton getGrabar() {
        return grabar;
    }

    public void setGrabar(JButton grabar) {
        this.grabar = grabar;
    }

    public JLabel getLeyenda() {
        return leyenda;
    }

    public void setLeyenda(JLabel leyenda) {
        this.leyenda = leyenda;
    }

    public JRadioButton getMale() {
        return male;
    }

    public void setMale(JRadioButton male) {
        this.male = male;
    }

    public JTextField getPrice() {
        return price;
    }

    public void setPrice(JTextField price) {
        this.price = price;
    }

    public JTextField getStyle() {
        return style;
    }

    public void setStyle(JTextField style) {
        this.style = style;
    }

    public JButton getPrint2() {
        return print2;
    }

    public void setPrint2(JButton print2) {
        this.print2 = print2;
    }
    
    
    /**
     * Creates new form Rhaircut
     * @param parent
     * @param modal
     */
    public Rhaircut(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Haircut");
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        panel3 = new org.edisoncor.gui.panel.Panel();
        header2 = new org.edisoncor.gui.panel.Panel();
        cent2 = new javax.swing.JPanel();
        LDinam2 = new javax.swing.JPanel();
        Lperson2 = new javax.swing.JPanel();
        Ldni4 = new javax.swing.JLabel();
        Ldni5 = new javax.swing.JLabel();
        price = new javax.swing.JTextField();
        style = new javax.swing.JTextField();
        Ldni6 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        Lopciones2 = new javax.swing.JPanel();
        print2 = new javax.swing.JButton();
        grabar = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        footer = new javax.swing.JPanel();
        leyenda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        panel3.setMaximumSize(new java.awt.Dimension(737, 504));
        panel3.setLayout(new java.awt.BorderLayout());

        header2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/header/Haircut type.png"))); // NOI18N
        header2.setMaximumSize(new java.awt.Dimension(737, 75));
        header2.setMinimumSize(new java.awt.Dimension(737, 75));
        header2.setPreferredSize(new java.awt.Dimension(737, 75));

        javax.swing.GroupLayout header2Layout = new javax.swing.GroupLayout(header2);
        header2.setLayout(header2Layout);
        header2Layout.setHorizontalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
        );
        header2Layout.setVerticalGroup(
            header2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        panel3.add(header2, java.awt.BorderLayout.NORTH);

        cent2.setOpaque(false);
        cent2.setLayout(new java.awt.BorderLayout());

        LDinam2.setPreferredSize(new java.awt.Dimension(683, 100));

        Lperson2.setPreferredSize(new java.awt.Dimension(619, 85));

        Ldni4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        Ldni4.setForeground(new java.awt.Color(0, 0, 0));
        Ldni4.setText("Style:");

        Ldni5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        Ldni5.setForeground(new java.awt.Color(0, 0, 0));
        Ldni5.setText("Price:");

        price.setFont(new java.awt.Font("Serif", 1, 12)); // NOI18N
        price.setForeground(new java.awt.Color(0, 0, 0));
        price.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                priceFocusGained(evt);
            }
        });

        style.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        style.setForeground(new java.awt.Color(0, 0, 0));
        style.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                styleFocusGained(evt);
            }
        });

        Ldni6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        Ldni6.setForeground(new java.awt.Color(0, 0, 0));
        Ldni6.setText("Gender:");

        gender.add(male);
        male.setText("M");
        male.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                maleFocusGained(evt);
            }
        });

        gender.add(female);
        female.setText("F");
        female.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                femaleFocusGained(evt);
            }
        });

        javax.swing.GroupLayout Lperson2Layout = new javax.swing.GroupLayout(Lperson2);
        Lperson2.setLayout(Lperson2Layout);
        Lperson2Layout.setHorizontalGroup(
            Lperson2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lperson2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Lperson2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Ldni6, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(Ldni4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Lperson2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Lperson2Layout.createSequentialGroup()
                        .addComponent(style, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Ldni5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Lperson2Layout.createSequentialGroup()
                        .addComponent(male)
                        .addGap(18, 18, 18)
                        .addComponent(female))))
        );
        Lperson2Layout.setVerticalGroup(
            Lperson2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Lperson2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(Lperson2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(style, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ldni5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ldni4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Lperson2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ldni6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(male)
                    .addComponent(female))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout LDinam2Layout = new javax.swing.GroupLayout(LDinam2);
        LDinam2.setLayout(LDinam2Layout);
        LDinam2Layout.setHorizontalGroup(
            LDinam2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LDinam2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lperson2, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        LDinam2Layout.setVerticalGroup(
            LDinam2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LDinam2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lperson2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );

        cent2.add(LDinam2, java.awt.BorderLayout.CENTER);

        Lopciones2.setPreferredSize(new java.awt.Dimension(450, 40));

        print2.setText("Print");
        print2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        print2.setPreferredSize(new java.awt.Dimension(150, 30));
        print2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                print2FocusGained(evt);
            }
        });
        Lopciones2.add(print2);

        grabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/register.png"))); // NOI18N
        grabar.setBorderPainted(false);
        grabar.setContentAreaFilled(false);
        grabar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        grabar.setMaximumSize(new java.awt.Dimension(150, 30));
        grabar.setMinimumSize(new java.awt.Dimension(150, 30));
        grabar.setPreferredSize(new java.awt.Dimension(150, 30));
        grabar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                grabarFocusGained(evt);
            }
        });
        Lopciones2.add(grabar);

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/delete.png"))); // NOI18N
        delete.setBorderPainted(false);
        delete.setContentAreaFilled(false);
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.setMaximumSize(new java.awt.Dimension(150, 30));
        delete.setMinimumSize(new java.awt.Dimension(150, 30));
        delete.setPreferredSize(new java.awt.Dimension(150, 30));
        delete.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                deleteFocusGained(evt);
            }
        });
        Lopciones2.add(delete);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/exit.png"))); // NOI18N
        exit.setBorderPainted(false);
        exit.setContentAreaFilled(false);
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.setMaximumSize(new java.awt.Dimension(150, 30));
        exit.setMinimumSize(new java.awt.Dimension(150, 30));
        exit.setPreferredSize(new java.awt.Dimension(150, 30));
        exit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                exitFocusGained(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        Lopciones2.add(exit);

        cent2.add(Lopciones2, java.awt.BorderLayout.SOUTH);

        panel3.add(cent2, java.awt.BorderLayout.CENTER);

        footer.setPreferredSize(new java.awt.Dimension(450, 32));
        footer.setLayout(new java.awt.BorderLayout());

        leyenda.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        leyenda.setForeground(new java.awt.Color(0, 0, 0));
        footer.add(leyenda, java.awt.BorderLayout.CENTER);

        panel3.add(footer, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panel3, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void print2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_print2FocusGained
        String leyend = "print";
        getLeyenda().setText(leyend);
    }//GEN-LAST:event_print2FocusGained

    private void grabarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_grabarFocusGained
        String leyend = "Save";
        getLeyenda().setText(leyend);
    }//GEN-LAST:event_grabarFocusGained

    private void deleteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deleteFocusGained
        String leyend = "Eliminate the type of cut";
        getLeyenda().setText(leyend);
    }//GEN-LAST:event_deleteFocusGained

    private void exitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_exitFocusGained
        String leyend = "exit of view";
        getLeyenda().setText(leyend);
    }//GEN-LAST:event_exitFocusGained

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed

    }//GEN-LAST:event_exitActionPerformed

    private void styleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_styleFocusGained
        String leyend = "Enter the name of the type of haircut";
        getLeyenda().setText(leyend);
    }//GEN-LAST:event_styleFocusGained

    private void priceFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_priceFocusGained
         String leyend = "Enter the corresponding price";
        getLeyenda().setText(leyend);
    }//GEN-LAST:event_priceFocusGained

    private void maleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_maleFocusGained
        String leyend = "Male";
        getLeyenda().setText(leyend);
    }//GEN-LAST:event_maleFocusGained

    private void femaleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_femaleFocusGained
          String leyend = "Woman";
        getLeyenda().setText(leyend);
    }//GEN-LAST:event_femaleFocusGained

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LDinam2;
    private javax.swing.JLabel Ldni4;
    private javax.swing.JLabel Ldni5;
    private javax.swing.JLabel Ldni6;
    private javax.swing.JPanel Lopciones2;
    private javax.swing.JPanel Lperson2;
    private javax.swing.JPanel cent2;
    private javax.swing.JButton delete;
    private javax.swing.JButton exit;
    private javax.swing.JRadioButton female;
    private javax.swing.JPanel footer;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JButton grabar;
    private org.edisoncor.gui.panel.Panel header2;
    private javax.swing.JLabel leyenda;
    private javax.swing.JRadioButton male;
    private org.edisoncor.gui.panel.Panel panel3;
    private javax.swing.JTextField price;
    private javax.swing.JButton print2;
    private javax.swing.JTextField style;
    // End of variables declaration//GEN-END:variables
}
