/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerWorkPosition;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Jnatn'h
 */
public class Rworkposition extends javax.swing.JDialog {

    private ControllerWorkPosition controller;
    public void setController(ControllerWorkPosition controller){
        this.controller = controller;
        setListener();
    }
    public ControllerWorkPosition getController(){
        return controller;
    }
    private void setListener(){
        getExit().addActionListener(controller);
        getDelete().addActionListener(controller);
        getGrabar().addActionListener(controller);
        getPrint().addActionListener(controller);
        
    }
    public JButton getExit() {
        return exit;
    }

    public void setExit(JButton exit) {
        this.exit = exit;
    }

    
    public JButton getDelete() {
        return delete;
    }

    public void setDelete(JButton delete) {
        this.delete = delete;
    }

    public JButton getGrabar() {
        return grabar;
    }

    public void setGrabar(JButton grabar) {
        this.grabar = grabar;
    }

    public JLabel getLeyenda() {
        return leyenda;
    }

    public void setLeyenda(JLabel leyenda) {
        this.leyenda = leyenda;
    }

    public JTextField getPosition() {
        return position;
    }

    public void setPosition(JTextField position) {
        this.position = position;
    }

    public JButton getPrint() {
        return print;
    }

    public void setPrint(JButton print) {
        this.print = print;
    }
    
    
    
    /**
     * Creates new form Rworkposition
     * @param parent
     * @param modal
     */
    public Rworkposition(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Work Positión");
        setResizable(false);
        setLocationRelativeTo(null);
          setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        header = new org.edisoncor.gui.panel.Panel();
        cent = new javax.swing.JPanel();
        LDinam = new javax.swing.JPanel();
        Lperson = new javax.swing.JPanel();
        Ldni = new javax.swing.JLabel();
        position = new javax.swing.JTextField();
        Lopciones = new javax.swing.JPanel();
        print = new javax.swing.JButton();
        grabar = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        footer = new javax.swing.JPanel();
        leyenda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        panel1.setMaximumSize(new java.awt.Dimension(737, 504));
        panel1.setLayout(new java.awt.BorderLayout());

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/header/Work position.png"))); // NOI18N
        header.setMaximumSize(new java.awt.Dimension(737, 75));
        header.setMinimumSize(new java.awt.Dimension(737, 75));
        header.setPreferredSize(new java.awt.Dimension(450, 75));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 75, Short.MAX_VALUE)
        );

        panel1.add(header, java.awt.BorderLayout.NORTH);

        cent.setOpaque(false);
        cent.setLayout(new java.awt.BorderLayout());

        LDinam.setPreferredSize(new java.awt.Dimension(683, 100));

        Lperson.setPreferredSize(new java.awt.Dimension(0, 140));

        Ldni.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        Ldni.setForeground(new java.awt.Color(0, 0, 0));
        Ldni.setText("Positión:");

        position.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        position.setForeground(new java.awt.Color(0, 0, 0));
        position.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                positionFocusGained(evt);
            }
        });

        javax.swing.GroupLayout LpersonLayout = new javax.swing.GroupLayout(Lperson);
        Lperson.setLayout(LpersonLayout);
        LpersonLayout.setHorizontalGroup(
            LpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LpersonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ldni, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        LpersonLayout.setVerticalGroup(
            LpersonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LpersonLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Ldni, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(position, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout LDinamLayout = new javax.swing.GroupLayout(LDinam);
        LDinam.setLayout(LDinamLayout);
        LDinamLayout.setHorizontalGroup(
            LDinamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LDinamLayout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(Lperson, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        LDinamLayout.setVerticalGroup(
            LDinamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LDinamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lperson, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        cent.add(LDinam, java.awt.BorderLayout.CENTER);

        Lopciones.setPreferredSize(new java.awt.Dimension(450, 40));

        print.setText("Print");
        print.setBorderPainted(false);
        print.setContentAreaFilled(false);
        print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        print.setFocusPainted(false);
        print.setMaximumSize(new java.awt.Dimension(150, 30));
        print.setMinimumSize(new java.awt.Dimension(150, 30));
        print.setPreferredSize(new java.awt.Dimension(150, 30));
        print.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                printFocusGained(evt);
            }
        });
        Lopciones.add(print);

        grabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/register.png"))); // NOI18N
        grabar.setBorderPainted(false);
        grabar.setContentAreaFilled(false);
        grabar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        grabar.setFocusPainted(false);
        grabar.setMaximumSize(new java.awt.Dimension(150, 30));
        grabar.setMinimumSize(new java.awt.Dimension(150, 30));
        grabar.setPreferredSize(new java.awt.Dimension(150, 30));
        grabar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                grabarFocusGained(evt);
            }
        });
        Lopciones.add(grabar);

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/delete.png"))); // NOI18N
        delete.setBorderPainted(false);
        delete.setContentAreaFilled(false);
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.setFocusPainted(false);
        delete.setMaximumSize(new java.awt.Dimension(150, 30));
        delete.setMinimumSize(new java.awt.Dimension(150, 30));
        delete.setPreferredSize(new java.awt.Dimension(150, 30));
        delete.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                deleteFocusGained(evt);
            }
        });
        Lopciones.add(delete);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/exit.png"))); // NOI18N
        exit.setBorderPainted(false);
        exit.setContentAreaFilled(false);
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.setFocusPainted(false);
        exit.setMaximumSize(new java.awt.Dimension(150, 30));
        exit.setMinimumSize(new java.awt.Dimension(150, 30));
        exit.setPreferredSize(new java.awt.Dimension(150, 30));
        exit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                exitFocusGained(evt);
            }
        });
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        Lopciones.add(exit);

        cent.add(Lopciones, java.awt.BorderLayout.SOUTH);

        panel1.add(cent, java.awt.BorderLayout.CENTER);

        footer.setPreferredSize(new java.awt.Dimension(450, 32));
        footer.setLayout(new java.awt.BorderLayout());

        leyenda.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        leyenda.setForeground(new java.awt.Color(0, 0, 0));
        footer.add(leyenda, java.awt.BorderLayout.CENTER);

        panel1.add(footer, java.awt.BorderLayout.SOUTH);

        getContentPane().add(panel1, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_printFocusGained
        String leyend = "print";
        getLeyenda().setText(leyend);
    }//GEN-LAST:event_printFocusGained

    private void grabarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_grabarFocusGained
        String leyend = "Save";
        getLeyenda().setText(leyend);
    }//GEN-LAST:event_grabarFocusGained

    private void deleteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_deleteFocusGained
        String leyend = "Eliminate the position";
        getLeyenda().setText(leyend);
    }//GEN-LAST:event_deleteFocusGained

    private void exitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_exitFocusGained
        String leyend = "Get out";
        getLeyenda().setText(leyend);
    }//GEN-LAST:event_exitFocusGained

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed

    }//GEN-LAST:event_exitActionPerformed

    private void positionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_positionFocusGained
        String leyend = "Enter or modify the work position";
        getLeyenda().setText(leyend);
    }//GEN-LAST:event_positionFocusGained

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LDinam;
    private javax.swing.JLabel Ldni;
    private javax.swing.JPanel Lopciones;
    private javax.swing.JPanel Lperson;
    private javax.swing.JPanel cent;
    private javax.swing.JButton delete;
    private javax.swing.JButton exit;
    private javax.swing.JPanel footer;
    private javax.swing.JButton grabar;
    private org.edisoncor.gui.panel.Panel header;
    private javax.swing.JLabel leyenda;
    private org.edisoncor.gui.panel.Panel panel1;
    private javax.swing.JTextField position;
    private javax.swing.JButton print;
    // End of variables declaration//GEN-END:variables
}
