/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Controller.ControllerHaircut;
import Controller.ControllerMeeting;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import static javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE;




/**
 *
 * @author Jnatn'h
 */
public class Vhaircut extends javax.swing.JDialog {

    private ControllerHaircut controller;
    private ControllerMeeting controller1;
    public void setController(ControllerHaircut controller){
    this.controller = controller;
    setListener();
    }
    public void setController(ControllerMeeting controller){
        this.controller1 = controller;
        setListener(controller1);
    }
    public ControllerMeeting getController1(){
        return controller1;
    }
    
    public ControllerHaircut getController(){
    return controller;
    }
    private void setListener(){
        nuevo.addActionListener(controller);
        Textsearch.addKeyListener(controller);
        cathaircut.addMouseListener(controller);
    }
    private void setListener(ControllerMeeting controller){
        nuevo.addActionListener(controller);
        Textsearch.addKeyListener(controller);
        cathaircut.addMouseListener(controller);
    }
    public JTextField getTextsearch() {
        return Textsearch;
    }

    public void setTextsearch(JTextField Textsearch) {
        this.Textsearch = Textsearch;
    }

    public JTable getCathaircut() {
        return cathaircut;
    }

    public void setCathaircut(JTable cathaircut) {
        this.cathaircut = cathaircut;
    }

    public JLabel getLeyenda() {
        return leyenda;
    }

    public void setLeyenda(JLabel leyenda) {
        this.leyenda = leyenda;
    }

    public JButton getNew() {
        return nuevo;
    }

    public void setNew(JButton nuevo) {
        this.nuevo = nuevo;
    }
    
    /** Creates new form Vhaircut
     * @param parent
     * @param modal */
    public Vhaircut(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Haircut types");
        setResizable(false);
        setLocationRelativeTo(null);
       
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cat = new org.edisoncor.gui.panel.Panel();
        header = new org.edisoncor.gui.panel.Panel();
        center = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Textsearch = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        nuevo = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        cent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cathaircut = new javax.swing.JTable();
        footer = new javax.swing.JPanel();
        leyenda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        cat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/fondo.png"))); // NOI18N
        cat.setMaximumSize(new java.awt.Dimension(440, 451));
        cat.setPreferredSize(new java.awt.Dimension(440, 451));
        cat.setLayout(new java.awt.BorderLayout());

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/Haircut_Type.jpg"))); // NOI18N
        header.setMaximumSize(new java.awt.Dimension(464, 75));
        header.setOpaque(false);
        header.setPreferredSize(new java.awt.Dimension(464, 75));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        cat.add(header, java.awt.BorderLayout.NORTH);

        center.setOpaque(false);
        center.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(442, 40));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 2));

        Textsearch.setForeground(new java.awt.Color(0, 0, 0));
        Textsearch.setPreferredSize(new java.awt.Dimension(400, 37));
        Textsearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextsearchFocusGained(evt);
            }
        });
        Textsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextsearchKeyTyped(evt);
            }
        });
        jPanel2.add(Textsearch);

        center.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(448, 30));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/new.png"))); // NOI18N
        nuevo.setBorderPainted(false);
        nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuevo.setDefaultCapable(false);
        nuevo.setFocusPainted(false);
        nuevo.setMaximumSize(new java.awt.Dimension(150, 30));
        nuevo.setMinimumSize(new java.awt.Dimension(150, 30));
        nuevo.setOpaque(false);
        nuevo.setPreferredSize(new java.awt.Dimension(150, 30));
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        jPanel1.add(nuevo);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/exit.png"))); // NOI18N
        exit.setBorderPainted(false);
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.setDefaultCapable(false);
        exit.setFocusPainted(false);
        exit.setMaximumSize(new java.awt.Dimension(150, 30));
        exit.setMinimumSize(new java.awt.Dimension(150, 30));
        exit.setOpaque(false);
        exit.setPreferredSize(new java.awt.Dimension(150, 30));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);

        center.add(jPanel1, java.awt.BorderLayout.SOUTH);

        cent.setOpaque(false);
        cent.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 403));

        cathaircut.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        cathaircut.setForeground(new java.awt.Color(0, 0, 0));
        cathaircut.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Style", "Price", "Gender"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        cathaircut.setToolTipText("Users");
        cathaircut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cathaircut.setOpaque(false);
        cathaircut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cathaircutKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cathaircutKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(cathaircut);

        cent.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        center.add(cent, java.awt.BorderLayout.CENTER);

        cat.add(center, java.awt.BorderLayout.CENTER);

        footer.setBackground(new java.awt.Color(0, 102, 255));
        footer.setOpaque(false);
        footer.setPreferredSize(new java.awt.Dimension(0, 30));
        footer.setLayout(new java.awt.BorderLayout());

        leyenda.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        leyenda.setForeground(new java.awt.Color(0, 0, 0));
        footer.add(leyenda, java.awt.BorderLayout.CENTER);

        cat.add(footer, java.awt.BorderLayout.SOUTH);

        getContentPane().add(cat, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextsearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextsearchFocusGained
        String leyend = "Find the type of cut you want";
        getLeyenda().setText(leyend);
    }//GEN-LAST:event_TextsearchFocusGained

    private void TextsearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextsearchKeyTyped
        //
    }//GEN-LAST:event_TextsearchKeyTyped

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed

    }//GEN-LAST:event_nuevoActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        //  getController().getModel().conexionClosed();
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void cathaircutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cathaircutKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cathaircutKeyReleased

    private void cathaircutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cathaircutKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cathaircutKeyTyped

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Textsearch;
    private org.edisoncor.gui.panel.Panel cat;
    private javax.swing.JTable cathaircut;
    private javax.swing.JPanel cent;
    private javax.swing.JPanel center;
    private javax.swing.JButton exit;
    private javax.swing.JPanel footer;
    private org.edisoncor.gui.panel.Panel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel leyenda;
    private javax.swing.JButton nuevo;
    // End of variables declaration//GEN-END:variables

}
