/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerUsers;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Jnatn'h
 */
public class Vuser extends javax.swing.JDialog {

    private ControllerUsers Controller;

    public ControllerUsers getController() {
        return Controller;
    }

    public void setController(ControllerUsers Controller) {
        this.Controller = Controller;
        asignarlistener();
    }
    
     private void asignarlistener(){
        Textbusqueda.addKeyListener(getController());
        catusers.addMouseListener(getController());
        nuevo.addActionListener(getController());
        exit.addActionListener(getController());
    }
    
    public JTable getCatusers() {
        return catusers;
    }

    public void setCatusers(JTable Cattipoempleado) {
        this.catusers = Cattipoempleado;
    }

    public JTextField getTextbusqueda() {
        return Textbusqueda;
    }

    public void setTextbusqueda(JTextField Textbusqueda) {
        this.Textbusqueda = Textbusqueda;
    }

    public JButton getExit() {
        return exit;
    }

    public void setExit(JButton exit) {
        this.exit = exit;
    }

    public JLabel getLeyenda() {
        return leyenda;
    }

    public void setLeyenda(JLabel leyenda) {
        this.leyenda = leyenda;
    }

    public JButton getNuevo() {
        return nuevo;
    }

    public void setNuevo(JButton nuevo) {
        this.nuevo = nuevo;
    }

    
    /**
     * Creates new form Vuser
     * @param parent
     * @param modal
     */
    public Vuser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Users");
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        setController(new ControllerUsers(this));
        this.centerWindow();
      
    }
    private void centerWindow() {
        //Obtiene el tamaño de la pantalla
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        // Obtiene el tamaño de la ventana de la aplicación
        Dimension frameSize = getSize();
        // Se asegura que el tamaño de la ventana de la aplicación
        // no exceda el tamaño de la pantalla
        if (frameSize.height > screenSize.height) {
        frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
        frameSize.width = screenSize.width;
        }
        // Centra la ventana de la aplicación sobre la pantalla
        setLocation((screenSize.width - frameSize.width) / 2,
        (screenSize.height - frameSize.height) / 2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cat = new org.edisoncor.gui.panel.Panel();
        header = new org.edisoncor.gui.panel.Panel();
        center = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Textbusqueda = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        nuevo = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        cent = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        catusers = new javax.swing.JTable();
        footer = new javax.swing.JPanel();
        leyenda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(440, 451));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        cat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/fondo.png"))); // NOI18N
        cat.setMaximumSize(new java.awt.Dimension(464, 422));
        cat.setLayout(new java.awt.BorderLayout());

        header.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/lusers.png"))); // NOI18N
        header.setMaximumSize(new java.awt.Dimension(464, 75));
        header.setOpaque(false);
        header.setPreferredSize(new java.awt.Dimension(464, 75));

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        cat.add(header, java.awt.BorderLayout.NORTH);

        center.setOpaque(false);
        center.setLayout(new java.awt.BorderLayout(0, 10));

        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(442, 40));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 2));

        Textbusqueda.setPreferredSize(new java.awt.Dimension(400, 37));
        Textbusqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TextbusquedaFocusGained(evt);
            }
        });
        Textbusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextbusquedaKeyTyped(evt);
            }
        });
        jPanel2.add(Textbusqueda);

        center.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(448, 30));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/new.png"))); // NOI18N
        nuevo.setBorderPainted(false);
        nuevo.setContentAreaFilled(false);
        nuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nuevo.setFocusPainted(false);
        nuevo.setPreferredSize(new java.awt.Dimension(150, 30));
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        jPanel1.add(nuevo);

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/exit.png"))); // NOI18N
        exit.setBorderPainted(false);
        exit.setContentAreaFilled(false);
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.setFocusPainted(false);
        exit.setPreferredSize(new java.awt.Dimension(150, 30));
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);

        center.add(jPanel1, java.awt.BorderLayout.SOUTH);

        cent.setOpaque(false);
        cent.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setOpaque(false);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 403));

        catusers.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        catusers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Dni", "User"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        catusers.setToolTipText("Users");
        catusers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        catusers.setOpaque(false);
        catusers.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                catusersKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                catusersKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(catusers);

        cent.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        center.add(cent, java.awt.BorderLayout.CENTER);

        cat.add(center, java.awt.BorderLayout.CENTER);

        footer.setBackground(new java.awt.Color(0, 102, 255));
        footer.setOpaque(false);
        footer.setPreferredSize(new java.awt.Dimension(0, 30));
        footer.setLayout(new java.awt.BorderLayout());

        leyenda.setFont(new java.awt.Font("Serif", 2, 14)); // NOI18N
        leyenda.setForeground(new java.awt.Color(0, 0, 0));
        footer.add(leyenda, java.awt.BorderLayout.CENTER);

        cat.add(footer, java.awt.BorderLayout.SOUTH);

        getContentPane().add(cat, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void catusersKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_catusersKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_catusersKeyReleased

    private void catusersKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_catusersKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_catusersKeyTyped

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed

    }//GEN-LAST:event_nuevoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        getController().getModel().conexionClosed();
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void TextbusquedaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TextbusquedaFocusGained
        String leyenda = "Search the corresponding user";
        getLeyenda().setText(leyenda);
    }//GEN-LAST:event_TextbusquedaFocusGained

    private void TextbusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextbusquedaKeyTyped
      this.validar(evt);
    }//GEN-LAST:event_TextbusquedaKeyTyped
    private void validar (KeyEvent e){
        char b = e.getKeyChar();
        
//         if(b != KeyEvent.VK_SPACE){
//            e.consume();
//         }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Textbusqueda;
    private org.edisoncor.gui.panel.Panel cat;
    private javax.swing.JTable catusers;
    private javax.swing.JPanel cent;
    private javax.swing.JPanel center;
    private javax.swing.JButton exit;
    private javax.swing.JPanel footer;
    private org.edisoncor.gui.panel.Panel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel leyenda;
    private javax.swing.JButton nuevo;
    // End of variables declaration//GEN-END:variables
}
